from django.urls import path
from . import views

urlpatterns = [
    path('',views.login_view,name='login_view'),
    path('reset/<str:token>/', views.reset_password_view, name='reset_password'),
    path('admin_dashboard/', views.admin_home, name='admin_dashboard'),
    path('dashboard/', views.emp_home, name='emp_dashboard'),
    path('add_employee/', views.add_employee, name='add_employee'),
    path('upload_attendance/', views.upload_attendance, name='upload_attendance'),
    path('', views.login_view, name='logout'),
    path('get_designations/', views.get_designations, name='get_designations'),
    path('employees/', views.view_employees, name='view_employees'),
    path('search-employees/', views.search_employees, name='search_employees'),
    path('employee/edit/<int:employee_id>/', views.edit_employee, name='edit_employee'),
    path('leave-requests/', views.leave_requests, name='leave_requests'),
    path('approve-leave/<int:leave_record_id>/', views.approve_leave, name='approve-leave'),
    path('predict-salary/', views.salary_prediction_view, name='predict_salary'),
    path('leave/', views.submit_leave_request, name='submit_leave_request'),
    path('tax_input/', views.tax_input_view, name='tax_input'),
    path('salary/operations/', views.salary_operations_view, name='salary_operations'),
    path('summa', views.summa, name='summa'),
    path('payslip/<int:month>/<int:year>/', views.payslip_view, name='payslip'),
    path('generate-payslip/<int:emp_id>/<str:month>/<int:year>/', views.generate_payslip, name='generate_payslip'),

    path('check_processing/', views.check_processing, name='check_processing'),
    path('emp_dashboard/', views.emp_dashboard, name='emp_dashboard'),
    path('attendance/', views.attendance_view, name='attendance'),
    path('salary/', views.salary_details, name='salary'),
    path('notify/', views.notify, name='notify'),
    path('mark-notification-as-read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('notifications/<str:category>/', views.category_notifications, name='category_notifications'),
    path('mark-all-as-read/<str:category>/', views.mark_all_as_read, name='mark_all_as_read'),
    path('report/', views.DownloadSalaryReportPDF.as_view(), name='report'),
    path('download-salary-excel/', views.DownloadSalaryReportExcel.as_view(), name='salary_excel_report'),
    path('report_view/',views.report_view,name='report_view'),
    path('financial-report/<int:year>', views.AnnualFinancialReportPDF.as_view(), name='financial-report'),
    path('upload/', views.upload_resume, name='upload_resume'),
    path('chatbot/',views.chatbot_view,name='chatbot'),
    path('chatbot-reply/', views.chatbot_reply, name='chatbot-reply'),
]
